# Check coding standards and static code analysis
name: Code Analysis

on:
  # Runs on pushes and pull requests targeting the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read

jobs:
  # Check PHP Coding Standards
  lintphp:
    name: Analyse PHP
    runs-on: ubuntu-latest
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Composer
        run: |
          composer config -g github-oauth.github.com ${{ secrets.COMPOSER_AUTH_TOKEN }}
          composer validate --strict
          composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      - name: Coding Standards
        run: composer run phpcs

      - name: Static Analysis
        run: composer run phpstan

      - name: PHPUnit Testing
        run: composer run phpunit

      - name: Coverage Check
        run: composer run coverage

  # Check SASS, CSS and JS Coding Standards
  lintcss:
    name: Analyse SASS, CSS and JS
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Packages
        run: npm install --silent --no-progress

      - name: Check Standards
        run: npm run check
